### ISSUE TITLE
after adding template = ihe.fhir.template to IG.ini, the latest base template is not used

### ISSUE THREAD

**Issue by vassilpeytchev** [IHE/supplement-template#31]
The current (not released) base template has the update to menus to take up 30% of the screen. After IG.ini was updated, that feature is not available.

**Comment by JohnMoehrke** [comment]
This is not an IHE problem. HL7 has not released the HL7 template with that wider menu. Thus you need to force the use of #current template.

Thus in your ig.ini use to use unreleased templates
template = ihe.fhir.template#current

rather than without "#current" which uses released templates.

HL7 needs to release their base template with the fix you desire.  The use of #current is okay for development, but as we approach release to public comment or beyond we need to be using only released templates. Please stress your need to HL7.
